---
- name: Restart the Docker service
  ansible.builtin.service:
    name: docker
    state: restarted
  listen: docker_service_manage
  when: docker_service_manage | bool

- name: Ensure Docker service state
  ansible.builtin.service:
    name: docker
    state: "{{ docker_service_state_running }}"
    enabled: "{{ docker_service_state_enabled }}"
  listen: docker_service_manage
  when: docker_service_manage | bool
