name: CI

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: averagebit.docker

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase.
        uses: actions/checkout@v2
        with:
          path: averagebit.docker

      - name: Install Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pip dependencies.
        run: pip3 install yamllint

      - name: Lint codebase.
        run: |
          yamllint .
